use adv
CREATE TABLE JobFairLogs
(
    Id INT IDENTITY PRIMARY KEY,
    ProjectId UNIQUEIDENTIFIER NOT NULL,
    EmployeeId UNIQUEIDENTIFIER NOT NULL,
    RManagerId UNIQUEIDENTIFIER NOT NULL,
    Hire BIT NOT NULL,
    LogDate DATETIME NOT NULL DEFAULT GETDATE()
);